#! /bin/bash -f

BOX=5.0
NPART=100
NSTEP=50000
NINIT=5000
TEMP=0.8
DELTAT=0.005

# Q3: Energy drift as a function of time step
for TEMP in 0.1 0.3 0.5 0.7
do
for DELTAT in 0.0001 0.0004 0.0005 0.0007 0.0009 0.001 0.003 0.005 0.007 0.009
do
cat > input <<endofdata
$BOX    $NPART $NSTEP  $TEMP  $DELTAT $NINIT
endofdata
time ../Source/md_nve > output
DELTAU=$(grep "Average DeltaU" output | awk '{print $NF}')
echo $DELTAT $DELTAU >> drift-euler-$TEMP.dat
rm input output
done
done
exit

# Q5: Self-diffusion coefficient
# cat > input <<endofdata
# $BOX    $NPART $NSTEP  $TEMP  $DELTAT $NINIT
# endofdata
# time ../Source/md_nve
# rm input
# exit
