#! /bin/bash -f

BOX=5.0
NPART=100
NSTEP=50000
NINIT=5000
TEMP=0.8
DELTAT=0.005

# Q3: Energy drift as a function of time step
for TEMP in #values
do
for DELTAT in #values
do
cat > input <<endofdata
$BOX    $NPART $NSTEP  $TEMP  $DELTAT $NINIT
endofdata
time ../Source/md_nve > output
DELTAU=$(grep "Average DeltaU" output | awk '{print $NF}')
echo $DELTAT $DELTAU >> drift-euler-$TEMP.dat
rm input output
done
done
exit

# Q5: Self-diffusion coefficient
# cat > input <<endofdata
# $BOX    $NPART $NSTEP  $TEMP  $DELTAT $NINIT
# endofdata
# time ../Source/md_nve
# rm input
# exit
